### ISSUE TITLE
JSS7 Fails to Compile

### ISSUE THREAD

**Issue by xq1xq1xq1** [P1sec/SigFW#13]
mvn clean install -Dmaven.test.skip=true

    fails with error 
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 06:37 min
    [INFO] Finished at: 2018-10-01T12:23:32-06:00
    [INFO] Final Memory: 50M/89M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project scheduler: Compilation failure: Compilation failure: 
    [ERROR] error: Source option 5 is no longer supported. Use 6 or later.
    [ERROR] error: Target option 1.5 is no longer supported. Use 1.6 or later.
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :scheduler

hardware configuration: HP Elite Desktop 00 G1

OS: UBuntu 18.04

Kernel (e.g. uname -a): Linux stc0042223 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09     UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    Package: maven
    Architecture: all
    Version: 3.5.2-2
    Priority: optional
    Section: universe/java
    Origin: Ubuntu

mvn -version
    Apache Maven 3.5.2
    Maven home: /usr/share/maven
    Java version: 10.0.2, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-10-oracle
    Default locale: en_CA, platform encoding: UTF-8
    OS name: "linux", version: "4.15.0-36-generic", arch: "amd64", family: "unix"

**Comment by p1-martin** [comment]
Have you changed the pom.xml?
Can you check your source and target compiler options in the pom.xml?

`            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
`

or it can be defined in these properties. Check what is your version.
`<properties>
<maven.compiler.source>1.7</maven.compiler.source>
<maven.compiler.target>1.7</maven.compiler.target>
 </properties>
`

**Comment by xq1xq1xq1** [comment]
I assume you are referring to the JSS7 pom.xml file located at the root of the JSS7 directory.

I have not changed the pom.xml file from what was downloaded.

The only section I can find in this file that references the maven-compiler is

     <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>${compiler.plugin.version}</version>
                                <configuration>
                                        <source>${compile.source}</source>
                                        <target>${compile.source}</target>
                                        <debug>${compile.debug}</debug>
                                </configuration>
                        </plugin>

The corresponding properties from the top of the pom.xml file are:

        <properties>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

                
                <restcomm.tools.mavenplugin.eclipse.version>
                        1.0.0.FINAL
                </restcomm.tools.mavenplugin.eclipse.version>
                
                <telscale.checkstyle.version>1.0.0.FINAL</telscale.checkstyle.version>
                <checkstyle.plugin.version>2.9.1</checkstyle.plugin.version> 
                <maven-surefire-plugin.version>2.19.1</maven-surefire-plugin.version> 
                <concurrent.version>1.3.4</concurrent.version>
                <log4j.version>1.2.14</log4j.version>
                <junit.version>3.8.1</junit.version>
                <testng.version>6.2</testng.version>
                <javolution.version>5.5.1</javolution.version>
                <compiler.plugin.version>2.0.2</compiler.plugin.version>
                <compile.source>1.7</compile.source>
                
                <asn.version>2.2.0-143</asn.version>
                <stream.version>1.0.0.CR1</stream.version>
                <sctp.version>2.0.0-166</sctp.version>
                <commons.version>1.0.0.CR1</commons.version>
                <netty.version>4.0.33.Final</netty.version>


                <version.wildfly.as>10.1.0.Final</version.wildfly.as>
                <version.wildfly.core>2.2.0.Final</version.wildfly.core>

                
        </properties>

I do not see maven.compiler.source in this pom.xml file, is there another location that I should be looking in?

    # find / -name "pom.xml" -type f | xargs grep "maven.compiler.source"


Thanx for your help!

**Comment by p1-martin** [comment]
It looks like that your are building jSS7 project from source. For building jSS7 from source you should follow the issue on jSS7 github.

SigFW project uses jSS7 as library and it is not required to compile the jSS7 from source. jSS7 library is referenced in [pom.xml](https://github.com/P1sec/SigFW/blob/master/sigfw/sigfw.sigfw/pom.xml) in SigFW repo. There is also defined the compiler version on line [295, 296](https://github.com/P1sec/SigFW/blob/master/sigfw/sigfw.sigfw/pom.xml#L295). 

Try to build SigFW project only to check if this works for you or not. Try following: 
* clone SigFW repo `git clone https://github.com/P1sec/SigFW.git`
* run `mvn clean install -Dmaven.test.skip=true` in folder `sigfw/sigfw.sigfw` where is located pom.xml (the jSS7 libraries should be downloaded during the built process).

**Comment by xq1xq1xq1** [comment]
I now have this error:

    [INFO] ------------------------------------------------------------------------
    [[INFO] BUILD FAILURE
    [[INFO] ------------------------------------------------------------------------
    [[INFO] Total time: 02:45 min
    [[INFO] Finished at: 2018-10-04T13:02:07-06:00
    [[INFO] Final Memory: 19M/62M
    [[INFO] ------------------------------------------------------------------------
    [[ERROR] Failed to execute goal on project SigFW: Could not resolve dependencies for project [com.p1sec:SigFW:jar:1.0.0: The following artifacts could not be resolved:                 [com.sun.jdmk:jmxtools:jar:1.2.1, com.vendor.dialogic:gctapi:jar:6.7.1, com.p1sec.sigfw:SigFW_interface:jar:1.0: Could not find artifact com.sun.jdmk:jmxtools:jar:1.2.1 in central (https://repo.maven.apache.org/maven2), try downloading from http://java.sun.com/products/JavaManagement/download.html -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I then installed jdk-11_linux-x64_bin.deb from https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html and tried again

with this error:

    [ERROR] Failed to execute goal on project SigFW: Could not resolve dependencies for project com.p1sec:SigFW:jar:1.0.0: The following artifacts could not be resolved: com.sun.jdmk:jmxtools:jar:1.2.1, com.vendor.dialogic:gctapi:jar:6.7.1, com.p1sec.sigfw:SigFW_interface:jar:1.0: Failure to find com.sun.jdmk:jmxtools:jar:1.2.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Ideas?

Thanx so much for your assistance!

**Comment by xq1xq1xq1** [comment]
I should have documented that I performed these steps at the start of this installation:

    # Install Oracle JDK 10
    sudo add-apt-repository ppa:linuxuprising/java
    sudo apt-get install oracle-java10-installer
    sudo apt install oracle-java10-set-default

    # Download netbeans 
    # from http://bits.netbeans.org/download/trunk/nightly/latest/
    bash ./netbeans-trunk-nightly-201804200002-javase-linux.sh

I then downloaded jdk-10.0.2_linux-x64_bin.tar.gz from https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html and extracted it into the Downloads directory (I did not see any method of installing after that)

    $ java -version
    java version "10.0.2" 2018-07-17
    Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

Ideas?

Hope I'm being dense

**Comment by xq1xq1xq1** [comment]
I found jmxtools in the repo which makes me even more confused:

    $ locate "jmxtools"
    /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools
    /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools/1.2.1
    /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools/1.2.1/_remote.repositories
    /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar.lastUpdated
    /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.pom
    /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.pom.sha1

**Comment by p1-martin** [comment]
Currently the same pre-requirements are required as for jSS7, documented [here](https://github.com/RestComm/jss7/wiki/Build-jSS7-from-Source)). Perform the following:

**resolve gctapi**:
Download Dialogic dependencies from Dialogic website. This is required to build the hardware part of jSS7 to have support for Dialogic boards in case you can't use SIGTRAN directly: `wget https://www.dialogic.com/files/DSI/developmentpackages/linux/dpklnx.Z`
Unpack the contents of the Dialogic SS7 dependencies: `tar --no-same-owner -zxvf dpklnx.Z`
Install the Dialogic SS7 Java Dependency in your local maven repository: `mvn install:install-file -DgroupId=com.vendor.dialogic -DartifactId=gctapi -Dversion=6.7.1 -Dpackaging=jar -Dfile=./JAVA/gctApi.jar`

**resolve jmxtools**:
Download Sun JMX tools dependency used by the jSS7 simulator : `wget http://www.datanucleus.org/downloads/maven2/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar`
Install the Sun JMX Tools Dependency in your local maven repository : `mvn install:install-file -DgroupId=com.sun.jdmk -DartifactId=jmxtools -Dversion=1.2.1 -Dpackaging=jar -Dfile=jmxtools-1.2.1.jar`

**resolve SigFW_interface**:
Run `mvn clean install -Dmaven.test.skip=true` first in `sigfw/sigfw_interface` directory. This maven project is part of SigFW repository.

**rebuild the SigFW project** (`mvn clean install -Dmaven.test.skip=true` in folder `sigfw/sigfw.sigfw`).

How to build SigFW is also documented [here](https://github.com/P1sec/SigFW/wiki/Installation-and-Build-Instructions) in wiki pages.

**Comment by xq1xq1xq1** [comment]
Thanx so much for your guidance.

The Resolve SIGFW_Interfaces failed during the build but I did not notice that in your notes you say "First in" but I do not see a second part.

thoughts?

Thanx again!

Here is my output:

Diaglogic - Success:
+++++++++++++++++++

    wget https://www.dialogic.com/files/DSI/developmentpackages/linux/dpklnx.Z
    --2018-10-05 06:31:18--  https://www.dialogic.com/files/DSI/developmentpackages/linux/dpklnx.Z
    Resolving www.dialogic.com (www.dialogic.com)... 104.247.34.146
    Connecting to www.dialogic.com (www.dialogic.com)|104.247.34.146|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 30312113 (29M) [application/x-compress]
    Saving to: ‘dpklnx.Z’

    dpklnx.Z                                     100%[===========================================================================================>]  28.91M  1.94MB/s    in 17s     

    2018-10-05 06:31:36 (1.69 MB/s) - ‘dpklnx.Z’ saved [30312113/30312113]

    sifgw@stc0042223:~/Downloads$ tar --no-same-owner -zxvf dpklnx.Z

    sifgw@stc0042223:~/Downloads$ mvn install:install-file -DgroupId=com.vendor.dialogic -DartifactId=gctapi -Dversion=6.7.1 -Dpackaging=jar -Dfile=./JAVA/gctApi.jar
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
    WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] ------------------------------------------------------------------------
    [INFO] Building Maven Stub Project (No POM) 1
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
    .
    .
    .
    [INFO] Installing /home/sifgw/Downloads/JAVA/gctApi.jar to /home/sifgw/.m2/repository/com/vendor/dialogic/gctapi/6.7.1/gctapi-6.7.1.jar
    [INFO] Installing /tmp/mvninstall14183193213876759054.pom to /home/sifgw/.m2/repository/com/vendor/dialogic/gctapi/6.7.1/gctapi-6.7.1.pom
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 6.165 s
    [INFO] Finished at: 2018-10-05T06:32:02-06:00
    [INFO] Final Memory: 10M/40M
    [INFO] ------------------------------------------------------------------------

JMXTools - Success:
+++++++++++++++++++

    $ wget http://www.datanucleus.org/downloads/maven2/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar
    --2018-10-05 06:32:21--  http://www.datanucleus.org/downloads/maven2/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar
    Resolving www.datanucleus.org (www.datanucleus.org)... 80.86.85.8
    Connecting to www.datanucleus.org (www.datanucleus.org)|80.86.85.8|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 102394 (100K) [application/java-archive]
    Saving to: ‘jmxtools-1.2.1.jar’

    jmxtools-1.2.1.jar                           100%[===========================================================================================>]  99.99K   201KB/s    in 0.5s    

    2018-10-05 06:32:22 (201 KB/s) - ‘jmxtools-1.2.1.jar’ saved [102394/102394]

    sifgw@stc0042223:~/Downloads$ mvn install:install-file -DgroupId=com.sun.jdmk -DartifactId=jmxtools -Dversion=1.2.1 -Dpackaging=jar -Dfile=jmxtools-1.2.1.jar
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
    WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] ------------------------------------------------------------------------
    [INFO] Building Maven Stub Project (No POM) 1
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
    [INFO] Installing /home/sifgw/Downloads/jmxtools-1.2.1.jar to /home/sifgw/.m2/repository/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 0.292 s
    [INFO] Finished at: 2018-10-05T06:32:31-06:00
    [INFO] Final Memory: 7M/37M
    [INFO] ------------------------------------------------------------------------

Rebuild SigFW_interface - Failure:
+++++++++++++++++++++++++++++++++++

    sifgw@stc0042223:~/Downloads/SigFW/sigfw$ cd sigfw.sigfw/
    sifgw@stc0042223:~/Downloads/SigFW/sigfw/sigfw.sigfw$ mvn clean install -Dmaven.test.skip=true
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
    WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] ------------------------------------------------------------------------
    [INFO] Building SigFW :: SigFW core 1.0.0
    [INFO] ------------------------------------------------------------------------
    Downloading from central: https://repo.maven.apache.org/maven2/com/p1sec/sigfw/SigFW_interface/1.0/SigFW_interface-1.0.pom
    [WARNING] The POM for com.p1sec.sigfw:SigFW_interface:jar:1.0 is missing, no dependency information available
    Downloading from central: https://repo.maven.apache.org/maven2/com/p1sec/sigfw/SigFW_interface/1.0/SigFW_interface-1.0.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1.727 s
    [INFO] Finished at: 2018-10-05T06:33:37-06:00
    [INFO] Final Memory: 18M/75M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project SigFW: Could not resolve dependencies for project com.p1sec:SigFW:jar:1.0.0: Could not find artifact com.p1sec.sigfw:SigFW_interface:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by xq1xq1xq1** [comment]
I initiallly made a typo and build the interface from the wrong directory.

I then went to the correct directly and it built successfully.

Then the SIGFW also built correctly.

Thanx so much for your assistance!
