### ISSUE TITLE
Question regarding Alerts

### ISSUE THREAD

**Issue by chrispatt454** [P1sec/SigFW#23]
Hi All,

Sorry to raise another ticket, I just have one query in regards to the SS7 firewall.
Is there any way to find the alerts raised/ packets dropped etc.? I don't have MThreat, so trying to figure out how I would see malicious traffic if flagged.

Thanks guys,

Chris

**Comment by p1-martin** [comment]
You can access the log files as described in the [wiki pages](https://github.com/P1sec/SigFW/wiki/Installation-and-Build-Instructions#check-logs). There are logs files `./SigFW/sigfw/sigfw.sigfw/ss7fw.log` and `./SigFW/sigfw/sigfw.sigfw/diameterfw.log` being created by log4j. Alerts are being logged in the firewallMessage method in DiameterFirewall and SS7Firewall class with info severity. The log4j verbosity is defined in the file `log4j.properties`.

**Comment by chrispatt454** [comment]
Thanks so much, really appreciate the swift response, please go ahead and close, and thanks again! You guys are awesome! :)
