### ISSUE TITLE
How to access and Enable mThreat

### ISSUE THREAD

**Issue by mmali277** [P1sec/SigFW#8]
I read the doc of SigFW, but i could not understand the part where it says how to enable mthreat i.e.
"Every firewalled event can be anonymized and send to mThreat. This optional capability and the
mThreat URL should be first enabled in the configuration file."
But i donot understand the file, i mean how to enable it here?
Your help will be highly appreciated.

![screenshot from 2018-02-08 17-17-15](https://user-images.githubusercontent.com/24794007/35972499-082d6978-0cca-11e8-98cc-e9ececee6dca.png)

**Comment by p1-martin** [comment]
@mmali277 
The mThreat is external server which is not included in this repository. However this part of configuration is controlling the SigFW mThreat connector (using REST API).

The mThreat connector is configured by this part of the firewall config as seen on the screenshot. If you remove this part from the config, the SigFW will not try to connect to mThreat server. Also if the mThreat server is not reachable it will less frequently connect.

The mThreat connector works in separate thread inside the firewall. Every signalling messages which is dropped by the firewall generates alert which is added into the alert list. The asynchronous thread is flushing these alerts from this list and over the REST API is forwarding them towards the mThreat server. The alerts are anonymized in SigFW code to not forward sensitive information.

The mThreat server source code is not included in the repository. If needed and after agreement we can provide access to our public server instance which can be used. Or you can deploy your server (for example by using jetty server processing this REST API and further processing these alerts)

**Comment by p1-martin** [comment]
I will close this issue for now, it can be reopened if needed.
