### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by ch0sys** [P1sec/SigFW#9]
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by p1-martin** [comment]
@ch0sys 
More details regarding this issue are required. What you have copied here is just generic maven dependency exception and for that you should follow the instructions there.

**Comment by ch0sys** [comment]
Hello. Please wait. For 4hours i send all details
